# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

aliases:
  - &docker
    - image: circleci/node:lts

  - &restore_yarn_cache
    restore_cache:
      name: Restore node_modules cache
      keys:
        - v1-node-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
        - v1-node-{{ arch }}-{{ .Branch }}-
        - v1-node-{{ arch }}-

  - &yarn_install
    run:
      name: Install Packages
      command: yarn install --frozen-lockfile

jobs:
  setup:
    docker: *docker

    steps:
      - checkout
      - *restore_yarn_cache
      - *yarn_install
      - save_cache:
          name: Save node_modules cache
          key: v1-node-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

  test:
    docker: *docker

    steps:
      - checkout
      - *restore_yarn_cache
      - *yarn_install
      # run tests!
      - run:
          name: Run Jest tests
          command: yarn ci:test

workflows:
  version: 2
  commit:
    jobs:
      - setup
      - test:
          requires:
            - setup
